# Generated by Django 5.0.2 on 2024-04-04 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0005_auto_20220208_1234"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="picture",),
    ]
